// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfrEiozFO4Zfmyx1DGUwS-2PNPFrgW7V0',
    appId: '1:622223434470:web:110da07342a886ee0b1127',
    messagingSenderId: '622223434470',
    projectId: 'notify-bc770',
    authDomain: 'notify-bc770.firebaseapp.com',
    storageBucket: 'notify-bc770.appspot.com',
    measurementId: 'G-SP0B6BLGKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJ6v5N4jnZfSv7k0-B2KXGXhcV6qX7_c',
    appId: '1:622223434470:android:b3a524f070b616de0b1127',
    messagingSenderId: '622223434470',
    projectId: 'notify-bc770',
    storageBucket: 'notify-bc770.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_SMZDDoJSE7tisZTRjgKfkKeFaSQUtQM',
    appId: '1:622223434470:ios:67ee4f6e5a0fcb290b1127',
    messagingSenderId: '622223434470',
    projectId: 'notify-bc770',
    storageBucket: 'notify-bc770.appspot.com',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_SMZDDoJSE7tisZTRjgKfkKeFaSQUtQM',
    appId: '1:622223434470:ios:67ee4f6e5a0fcb290b1127',
    messagingSenderId: '622223434470',
    projectId: 'notify-bc770',
    storageBucket: 'notify-bc770.appspot.com',
    iosBundleId: 'com.example.notify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfrEiozFO4Zfmyx1DGUwS-2PNPFrgW7V0',
    appId: '1:622223434470:web:ab1300b5db95c0a70b1127',
    messagingSenderId: '622223434470',
    projectId: 'notify-bc770',
    authDomain: 'notify-bc770.firebaseapp.com',
    storageBucket: 'notify-bc770.appspot.com',
    measurementId: 'G-GWPGKR6794',
  );
}
